package com.edesa.common;

public class AppConstant {
    
    public static Long ROLE_CUSTOMER = 1l;
    public static Long ROLE_ADMIN_MERCHANT = 2l;
    public static Long ROLE_ADMIN_MARKETPLACE = 3l;
    public static Long ROLE_SUPER_ADMIN_MARKETPLACE = 4l;

    public static Long PRODUCT_TRA_STATUS_1_NEW_TRANSACTION_BY_CUSTOMER = 1l;
    public static Long PRODUCT_TRA_STATUS_2_WAITING_FOR_PAYMENT_BY_CUSTOMER = 2l;
    public static long PRODUCT_TRA_STATUS_3_PAID_WAITNG_FOR_VERIFICATION_BY_SYSTEM = 3l;
    public static long PRODUCT_TRA_STATUS_4_PAYMENT_IS_VERIFED_BY_SYSTEM = 4l;
    public static long PRODUCT_TRA_STATUS_5_GOODS_ARE_PREPARED_BY_MERCHANT = 5l;
    public static long PRODUCT_TRA_STATUS_6_GOODS_ARE_READY_TO_BE_PICKED_CHANGED_BY_MERCHANT = 6l;
    public static long PRODUCT_TRA_STATUS_7_GOODS_ARE_BEING_DELIVERED_CHANGED_BY_MERCHANT = 7l;
    public static long PRODUCT_TRA_STATUS_8_GOODS_ARE_RECEIVED_BY_CUSTOMER = 8l;
    public static long PRODUCT_TRA_STATUS_9_TRANSACTION_IS_FINISHED_BY_SYSTEM = 9l;


    public static Long TREATMENT_TRA_STATUS_1_NEW_TRANSACTION_APPROVED_BY_MERCHANT = 101l;
    public static Long TREATMENT_TRA_STATUS_2_WAITING_FOR_PAYMENT_BY_CUSTOMER = 102l;
    public static long TREATMENT_TRA_STATUS_3_PAID_WAITNG_FOR_VERIFICATION_BY_SYSTEM = 103l;
    public static long TREATMENT_TRA_STATUS_4_PAYMENT_IS_VERIFED_BY_SYSTEM = 104l;
    public static long TREATMENT_TRA_STATUS_5_TRANSACTION_IS_FINISHED_BY_SYSTEM = 105l;


}
